accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.sign_up, name="signup"),
    path("login/", views.login, name="login"),
    path("<int:pk>/", views.detail, name="detail"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comment_create/", views.comment_creat, name="comment_create"),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/update/",
        views.comment_update,
        name="comment_update",
    ),
]

imagepjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    @property
    def full_name(self):
        return f"{self.last_name}{self.first_name}"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = [
            "username",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs = {
            "placeholder": "ID 입력",
            "class": "input-field",
        }
        self.fields["username"].help_text = None

        self.fields["password1"].widget.attrs = {
            "placeholder": "비밀번호 입력",
            "class": "input-field",
        }
        self.fields["password1"].help_text = None


class CustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as sy_login
from django.contrib.auth import logout as sy_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from .forms import CustomForm, CustomChangeForm
from django.contrib.auth.decorators import login_required


def sign_up(request):
    if request.method == "POST":
        form = CustomForm(request.POST)
        if form.is_valid():
            sy_login(request, form.save())
            return redirect("articles:index")

    else:
        form = CustomForm()

    context = {"form": form}
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            sy_login(request, form.get_user())
            return redirect(request.GET.get("next") or "articles:index")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    articles = user.article_set.all()
    comments = user.comment_set.all()
    context = {
        "user": user,
        "articles": articles,
        "comments": comments,
    }
    return render(request, "accounts/detail.html", context)


def logout(request):
    sy_logout(request)
    return redirect("articles:index")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomChangeForm(instance=request.user)

    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:detail", request.user.pk)
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/change_password.html", context)


# Create your views here.

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}



<body>
  <div class="container my-5">

    {% load django_bootstrap5 %}
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content="수정" %}


    </form>
  </div>

</body>
{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block content %}



<body>
  <div class="container my-5">


    <h1>{{ user.username }} 님의 프로필</h1>
    <p>{{ user.email }} | {{ user.full_name }}</p>
    <h2>작성글 {{ articles.count }} 개 </h2>
    <div>
      {% for article in articles %}
      <a class="title_link" href="{% url 'articles:detail' article.pk %}"> {{ article.title }} </a>
      <hr>
      {% empty %}
      <p>작성글이 없습니다.</p>
      {% endfor %}
    </div>

    <h2>작성 댓글</h2>
    <div>
      {% for comment in comments %}
      <a class="title_link" href="{% url 'articles:detail' comment.article_id %}"> {{ comment.content }} </a>
      <hr>
      {% empty %}
      <p>작성글이 없습니다.</p>
      {% endfor %}
    </div>

  </div>

</body>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block content %}

<body>
  <div class="container my-5">

    {% load django_bootstrap5 %}
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content="login" %}


    </form>
  </div>

</body>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}



<body>
  <div class="container my-5">

    {% load django_bootstrap5 %}
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content="signup" %}


    </form>
  </div>

</body>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}



<body>
  <div class="container my-5">


    <form action="" method="POST">
      {% csrf_token %}
      <div class="mb-3"><label class="form-label" for="id_first_name">First name</label><input type="text"
          name="first_name" value="{{request.user.first_name}}" maxlength="150" class="form-control"
          placeholder="First name" id="id_first_name"></div>
      <div class="mb-3"><label class="form-label" for="id_last_name">Last name</label><input type="text"
          name="last_name" value="{{request.user.last_name}}" maxlength="150" class="form-control"
          placeholder="Last name" id="id_last_name"></div>
      <div class="mb-3"><label class="form-label" for="id_email">Email address</label><input type="email" name="email"
          value="{{request.user.email}}" maxlength="254" class="form-control" placeholder="Email address" id="id_email">
      </div>
      <div class="mb-3"><label class="form-label" for="id_password">Password</label>
        <div class="form-control-static" disabled id="id_password">

          <strong>No password set.</strong>

        </div>
        <div class="form-text">Raw passwords are not stored, so there is no way to see this user’s password, but
          you can
          change the password using <a href="../password/">비밀번호 변경</a>.</div>
      </div>
      <button class="btn btn-primary" type="submit">수정</button>


    </form>

  </div>


</body>
{% endblock content %}