accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.sign_up, name="signup"),
    path("login/", views.login, name="login"),
    path("<int:pk>/", views.detail, name="detail"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comment_create/", views.comment_creat, name="comment_create"),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/update/",
        views.comment_update,
        name="comment_update",
    ),
]

imagepjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    image = models.ImageField(upload_to="images/", blank=True)
    thumbnail = ProcessedImageField(
        upload_to="images/",
        processors=[ResizeToFill(900, 1200)],
        format="JPEG",
        options={"quality": 80},
        blank=True,
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

articles/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .form import ArticleForm, CommentForm
from .models import Article, Comment
from django.contrib import messages
import os

# Create your views here.


def index(request):
    articles = Article.objects.all()
    context = {
        "articles": articles,
    }

    return render(request, "articles/index.html", context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    commentform = CommentForm()
    comments = article.comment_set.all()
    context = {
        "article": article,
        "commentform": commentform,
        "comments": comments,
    }
    return render(request, "articles/detail.html", context)


@login_required
def create(request):
    if request.method == "POST":
        article_form = ArticleForm(request.POST, request.FILES)
        if article_form.is_valid():
            article = article_form.save(commit=False)
            article.user = request.user
            article.save()
            messages.success(request, "등록되었습니다.")
            return redirect("articles:index")
    else:
        article_form = ArticleForm()

        context = {
            "form": article_form,
        }

    return render(request, "articles/create.html", context)


@login_required
def update(request, pk):
    article = Article.objects.get(id=pk)
    if request.user == article.user:
        if request.method == "POST":
            article_form = ArticleForm(
                request.POST, request.FILES, instance=Article.objects.get(pk=pk)
            )
            if article_form.is_valid():
                if (
                    article.image and request.FILES.get("image") != None
                ) or request.POST.get("image-clear"):
                    os.remove(article.image.path)
                if (
                    article.thumbnail and request.FILES.get("thumbnail") != None
                ) or request.POST.get("thumbnail-clear"):
                    os.remove(article.thumbnail.path)
                article_form.save()
                messages.success(request, "수정되었습니다.")
                return redirect("articles:detail", article.pk)
        else:
            article_form = ArticleForm(instance=Article.objects.get(pk=pk))

            context = {
                "form": article_form,
            }
        return render(request, "articles/update.html", context)
    else:
        return redirect("articles:index")


#  article = Article.objects.get(pk=pk)
#     form = ArticleForm(
#         request.POST or None, request.FILES or None, instance=Article.objects.get(pk=pk)
#     )
#     if form.is_valid():
#         print(request.FILES)
#         if (article.image and request.FILES.get("image") != None) or request.POST.get(
#             "image-clear"
#         ):
#             os.remove(article.image.path)
#         if (
#             article.thumbnail and request.FILES.get("thumbnail") != None
#         ) or request.POST.get("thumbnail-clear"):
#             os.remove(article.thumbnail.path)
#         form.save()
#         return redirect("articles:detail", pk)
#     context = {
#         "form": form,
#     }
#     return render(request, "articles/create.html", context)


@login_required
def delete(request, pk):
    article = Article.objects.get(id=pk)
    if request.user == article.user:
        if request.method == "POST":
            if article.image:
                os.remove(article.image.path)
            if article.thumbnail:
                os.remove(article.thumbnail.path)
            article.delete()
            return redirect("articles:index")
    else:
        return redirect("article:index")


@login_required
def comment_creat(request, pk):
    article = Article.objects.get(pk=pk)
    commentform = CommentForm(request.POST)
    if commentform.is_valid():
        comment = commentform.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect("articles:detail", article.pk)


@login_required
def comment_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
        return redirect("articles:detail", article_pk)
    else:
        return redirect("articles:detail", article_pk)


@login_required
def comment_update(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    article = Article.objects.get(pk=article_pk)
    if request.user == comment.user:
        if request.method == "POST":
            commentform = CommentForm(request.POST, instance=comment)
            if commentform.is_valid():
                comment = commentform.save(commit=False)
                comment.article = article
                comment.save()
                return redirect("articles:detail", article.pk)

        else:
            commentform = CommentForm(instance=comment)

        context = {
            "commentform": commentform,
        }
        return render(request, "articles/comment_update.html", context)
    else:
        return redirect("articles:detail", article.pk)

articles/templates/articles/comment_update.html
{% extends 'base.html' %}

{% block content %}


<body>

  <div class="container my-5">
    <h3 class="py-4">댓글 수정</h3>
    {% load django_bootstrap5 %}
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form commentform layout='inline' %}
      <br>
      {% bootstrap_button button_type="submit" content="ok" %}
    </form>
  </div>

</body>
{% endblock content %}

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}



<body>
  <div class="container my-5">

    {% load django_bootstrap5 %}
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content="Add" %}


    </form>
  </div>

</body>
{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}




<div class="container my-5">
  <div>
    <a class="title_link" href="{% url 'accounts:detail' article.user.pk%}">
      <h5 class="float-end"> {{ article.user.username }}</h5>
    </a>
    <h1>{{ article.title }}</h1>
  </div>
  <p>{{ article.content }}</p>
  <h2> 포토 </h2>
  <div class="d-flex">
    {% if article.image %}
    <img src="{{article.image.url}}">
    {% endif %}
  </div>
  <div class="my-3">
    {% if request.user.is_authenticated %}
    <h2>댓글</h2>
    {% load django_bootstrap5 %}
    <form action="{% url 'articles:comment_create' article.pk %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form commentform layout='inline' %}
      <br>
      {% bootstrap_button button_type="submit" content="댓글 작성" %}
    </form>
    {% endif %}


    <h5 class="mt-3"> 댓글 수 : {{article.comment_set.count}}</h5>
    <hr>

    {% for comment in comments %}

    <div>
      {% if request.user == comment.user %}
      <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <button class="float-end btn btn-dark m-1">댓글 삭제</button>
      </form>
      {% else %}

      {% endif %}

      <div class="d-flex justify-content-between">
        {% if request.user == comment.user %}
        <div><a href="{% url 'articles:comment_update' article.pk comment.pk %}" class="title_link">
            {{ comment.content }} </a> | {{ comment.created_at }} </div>
        <div> 작성자 <a class="title_link" href="{% url 'accounts:detail' comment.user.pk%}">
            {{ comment.user.username }}</a></div>
      </div>
      {% else %}
      <div>{{ comment.content }} | {{ comment.created_at }} </div>
      <div> 작성자 <a class="title_link" href="{% url 'accounts:detail' comment.user.pk%}">
          {{ comment.user.username }}</a></div>
    </div>
    {% endif %}
    <hr>
    {% empty %}
    <p>댓글이 없습니다.</p>
    {% endfor %}
  </div>
  <a class="float-end btn btn-dark m-1" href="{% url 'articles:index' %}">목록</a>
  {% if request.user == article.user %}
  <a class="float-end btn btn-danger m-1" href="{% url 'articles:update' article.pk %}"> 수정 </a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button class="float-end btn btn-primary m-1">삭제</button>
  </form>
  {% else %}
  <a class="float-end btn btn-danger m-1" data-bs-toggle="modal" data-bs-target="#exampleModal" href=""> 수정 </a>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <p>권한이 없습니다.</p>
          <div class="float-end">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">돌아가기</button>
          </div>
        </div>
      </div>
    </div>
    {% endif %}

  </div>


  {% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}

<body>
  <div class="container mt-5">
    <div class="row g-5">
      {% for article in articles %}
      <div class="col-12 col-sm-6 col-md-4 col-xl-3">
        <div class="card" style="width: 18rem;">
          {% if article.thumbnail %}

          <img src="{{ article.thumbnail.url }}" class="card-img-top">
          {% else %}
          <img src="https://dummyimage.com/900x1200/000000/c4c4c4" class="card-img-top">
          {% endif %}
          <div style="background-color: rgb(165, 163, 163);" class="card-body ">
            <h6 style="color: white;" class="card-title text-center">{{ article.title }}</h6>
            <a href="{% url 'articles:detail' article.pk %}" class="float-end btn btn-dark my-3">영화정보</a>
          </div>
        </div>
      </div>
      {% endfor %}
      {% if request.user.is_authenticated %}
      <a class="float-end btn btn-dark" href="{% url 'articles:create' %}">Registration</a>
      {% else %}
      <a class="float-end btn btn-dark m-1" data-bs-toggle="modal" data-bs-target="#exampleModal" href="">
        Registration </a>
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-body">
              <p>로그인 필요</p>
              <div class="float-end">
                <a class="btn btn-dark" href="/accounts/login/?next=/articles/create/">로그인</a>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">돌아가기</button>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>


</body>





{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}


<body>
  <div class="container my-5">

    {% load django_bootstrap5 %}
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content="OK" %}


    </form>
  </div>

</body>
{% endblock content %}